### ISSUE TITLE
Not working on Fedora 27

### ISSUE THREAD

**Issue by RobbiNespu** [flathub/com.github.ojubaorg.Othman#2]
It seem not working on F27

```bash
$ cat /etc/redhat-release 
Fedora release 27 (Twenty Seven)

 $ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=othman-browser com.github.ojubaorg.Othman --verbose
Traceback (most recent call last):
  File "/app/bin/othman-browser", line 3, in <module>
    from othman.gtkUi import main
  File "/app/lib/python2.7/site-packages/othman/gtkUi.py", line 23, in <module>
    from gi.repository import Gtk, Gdk, GLib, Pango, GdkPixbuf
  File "/app/lib/python2.7/site-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: /app/lib/python2.7/site-packages/gi/_gi.so: undefined symbol: PyUnicodeUCS2_AsUTF8String

$ flatpak info com.github.ojubaorg.Othman/x86_64/stable
Ref: app/com.github.ojubaorg.Othman/x86_64/stable
ID: com.github.ojubaorg.Othman
Arch: x86_64
Branch: stable
Origin: flathub
Date: 2017-09-12 09:54:55 +0000
Subject: Build com.github.ojubaorg.Othman at c34c87038f32cf82c1d670bdf783f4ff23a2a3cd
Commit: 8996c93124b6d1a93852ee09ad00e115bd420e71b601e4b36f3839493f68ec4b
Parent: -
Location: /var/lib/flatpak/app/com.github.ojubaorg.Othman/x86_64/stable/8996c93124b6d1a93852ee09ad00e115bd420e71b601e4b36f3839493f68ec4b
Installed size: 17.6 MB
Runtime: org.gnome.Platform/x86_64/3.24

```

**Comment by TingPing** [comment]
It should work after this rebuild: https://flathub.org/builds/#/builders/2/builds/36

**Comment by TingPing** [comment]
Ugh it fails to build of course.
